# Generated by Django 5.2.6 on 2025-10-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/skin_analyses/')),
                ('skin_type_prediction', models.CharField(blank=True, max_length=20, null=True)),
                ('skin_type_confidence', models.FloatField(blank=True, null=True)),
                ('acne_detected', models.BooleanField(default=False)),
                ('acne_severity', models.CharField(blank=True, max_length=20, null=True)),
                ('acne_confidence', models.FloatField(blank=True, null=True)),
                ('wrinkles_detected', models.BooleanField(default=False)),
                ('wrinkles_severity', models.CharField(blank=True, max_length=20, null=True)),
                ('wrinkles_confidence', models.FloatField(blank=True, null=True)),
                ('dark_spots_detected', models.BooleanField(default=False)),
                ('dark_spots_severity', models.CharField(blank=True, max_length=20, null=True)),
                ('dark_spots_confidence', models.FloatField(blank=True, null=True)),
                ('redness_detected', models.BooleanField(default=False)),
                ('redness_severity', models.CharField(blank=True, max_length=20, null=True)),
                ('redness_confidence', models.FloatField(blank=True, null=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('raw_cnn_results', models.JSONField(blank=True, default=dict)),
                ('raw_yolo_results', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_analyses', to='users.user')),
            ],
            options={
                'db_table': 'skin_analyses',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='SegmentationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmented_image', models.ImageField(upload_to='uploads/segmented/')),
                ('face_zone', models.JSONField(blank=True, default=dict)),
                ('acne_zones', models.JSONField(blank=True, default=list)),
                ('wrinkle_zones', models.JSONField(blank=True, default=list)),
                ('dark_spot_zones', models.JSONField(blank=True, default=list)),
                ('redness_zones', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skin_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation', to='detection.skinanalysis')),
            ],
            options={
                'db_table': 'segmentation_results',
            },
        ),
    ]
