# Generated by Django 5.2.6 on 2025-11-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinanalysis',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/skin_analyses/annotated/'),
        ),
    ]
