# Generated by Django 5.2.6 on 2025-10-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CLEANSER', 'Nettoyant'), ('MOISTURIZER', 'Hydratant'), ('SERUM', 'Sérum'), ('SUNSCREEN', 'Crème solaire'), ('TREATMENT', 'Traitement'), ('MASK', 'Masque'), ('TONER', 'Tonique'), ('EXFOLIANT', 'Exfoliant')], max_length=50)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('target_skin_types', models.JSONField(default=list)),
                ('target_issues', models.JSONField(default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.product')),
                ('skin_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='detection.skinanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.user')),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback_text', models.TextField(blank=True)),
                ('used_product', models.BooleanField(default=False)),
                ('purchase_intent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recommendations.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.user')),
            ],
            options={
                'db_table': 'user_feedbacks',
            },
        ),
    ]
