# Generated by Django 5.2.6 on 2025-10-15 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='Ingrédients')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Taille')),
                ('category', models.CharField(choices=[('CLEANSER', 'Nettoyant'), ('MOISTURIZER', 'Hydratant'), ('SERUM', 'Sérum'), ('SUNSCREEN', 'Crème solaire'), ('MASK', 'Masque'), ('TONER', 'Tonique'), ('EXFOLIANT', 'Exfoliant'), ('TREATMENT', 'Traitement')], max_length=50, verbose_name='Catégorie')),
                ('target_skin_types', models.JSONField(default=list, help_text='Liste des types de peau (SENSITIVE, DRY, OILY, COMBINATION, NORMAL)', verbose_name='Types de peau ciblés')),
                ('target_issues', models.JSONField(default=list, help_text='Liste des problèmes (acne, wrinkles, dark_spots, redness, dryness, oiliness)', verbose_name='Problèmes ciblés')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL du produit')),
                ('source_site', models.CharField(max_length=100, verbose_name='Site source')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='URL source')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('scraped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Scrapé par')),
            ],
            options={
                'verbose_name': 'Produit Scrapé',
                'verbose_name_plural': 'Produits Scrapés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=255, verbose_name='Nom de la session')),
                ('source_sites', models.JSONField(default=list, help_text='Liste des sites scrapés', verbose_name='Sites sources')),
                ('total_products_found', models.IntegerField(default=0, verbose_name='Total produits trouvés')),
                ('total_products_saved', models.IntegerField(default=0, verbose_name='Total produits sauvegardés')),
                ('total_products_skipped', models.IntegerField(default=0, verbose_name='Total produits ignorés')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Session de Scraping',
                'verbose_name_plural': 'Sessions de Scraping',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('SUCCESS', 'Succès')], max_length=20, verbose_name='Type de log')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scraped_products.scrapingsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Log de Scraping',
                'verbose_name_plural': 'Logs de Scraping',
                'ordering': ['-created_at'],
            },
        ),
    ]
