# Generated by Django 5.2.6 on 2025-10-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GANSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/gan/original/')),
                ('simulated_image', models.ImageField(upload_to='uploads/gan/simulated/')),
                ('simulation_type', models.CharField(choices=[('ACNE_TREATMENT', 'Traitement acné'), ('WRINKLE_REDUCTION', 'Réduction rides'), ('DARK_SPOT_REMOVAL', 'Suppression taches'), ('SKIN_SMOOTHING', 'Lissage peau'), ('COMPLETE_TREATMENT', 'Traitement complet')], max_length=20)),
                ('improvement_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('raw_gan_results', models.JSONField(blank=True, default=dict)),
                ('original_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gan_simulations', to='detection.skinanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gan_simulations', to='users.user')),
            ],
            options={
                'db_table': 'gan_simulations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_image', models.ImageField(upload_to='uploads/gan/comparison/before/')),
                ('after_image', models.ImageField(upload_to='uploads/gan/comparison/after/')),
                ('side_by_side_image', models.ImageField(upload_to='uploads/gan/comparison/side_by_side/')),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('improvement_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gan_simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to='gan.gansimulation')),
            ],
            options={
                'db_table': 'comparison_results',
            },
        ),
    ]
