# Generated by Django 5.2.6 on 2025-10-01 21:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], max_length=10, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('location_region', models.CharField(blank=True, max_length=100, null=True)),
                ('skin_type', models.CharField(blank=True, choices=[('DRY', 'Sèche'), ('OILY', 'Grasse'), ('COMBINATION', 'Mixte'), ('NORMAL', 'Normale'), ('SENSITIVE', 'Sensible')], max_length=20, null=True)),
                ('diabetes', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('blood_disorders', models.BooleanField(default=False)),
                ('autoimmune_diseases', models.BooleanField(default=False)),
                ('pregnancy', models.BooleanField(default=False)),
                ('sun_exposure', models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MODERATE', 'Modérée'), ('HIGH', 'Élevée')], max_length=20, null=True)),
                ('sunscreen_usage', models.CharField(blank=True, choices=[('NEVER', 'Jamais'), ('SOMETIMES', 'Parfois'), ('DAILY', 'Quotidiennement')], max_length=20, null=True)),
                ('diet', models.CharField(blank=True, choices=[('BALANCED', 'Équilibrée'), ('HIGH_FAT_SUGAR', 'Riche en graisses & sucres'), ('VEGETARIAN', 'Végétarienne')], max_length=20, null=True)),
                ('hydration', models.CharField(blank=True, choices=[('LOW', '<1L'), ('MODERATE', '1-2L'), ('HIGH', '>2L')], max_length=20, null=True)),
                ('smoking', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('sleep_hours', models.CharField(blank=True, choices=[('LOW', '<5h'), ('MODERATE', '5-7h'), ('HIGH', '>7h')], max_length=20, null=True)),
                ('family_dermatological_history', models.BooleanField(default=False)),
                ('current_skin_problems', models.JSONField(blank=True, default=list)),
                ('current_treatments', models.TextField(blank=True)),
                ('current_cosmetics', models.TextField(blank=True)),
                ('known_allergies', models.TextField(blank=True)),
                ('skin_goals', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
