# Generated by Django 5.2.6 on 2025-10-16 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Note de 1 à 5 étoiles')),
                ('comment', models.TextField(blank=True, help_text='Commentaire optionnel', null=True)),
                ('is_public', models.BooleanField(default=True, help_text="Afficher sur la page d'accueil")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
