# Generated by Django 5.2.6 on 2025-11-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertestimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alcohol_consumption',
            field=models.CharField(blank=True, choices=[('NONE', 'Aucune'), ('OCCASIONAL', 'Occasionnelle'), ('MODERATE', 'Modérée'), ('HIGH', 'Élevée')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='diet_quality',
            field=models.CharField(blank=True, choices=[('POOR', 'Faible'), ('AVERAGE', 'Moyenne'), ('GOOD', 'Bonne'), ('EXCELLENT', 'Excellente')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stress_level',
            field=models.IntegerField(blank=True, help_text='Niveau de stress de 1 à 10', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='alcohol',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('DRY', 'Sèche'), ('OILY', 'Grasse'), ('COMBINATION', 'Mixte'), ('NORMAL', 'Normale'), ('SENSITIVE', 'Sensible'), ('UNKNOWN', 'Je ne sais pas')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sleep_hours',
            field=models.IntegerField(blank=True, help_text="Nombre d'heures de sommeil par nuit", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='smoking',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
